FROM python:3.10-slim

WORKDIR /app

# system deps
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    libgl1 \
    libglib2.0-0 \
    fontconfig \
    && rm -rf /var/lib/apt/lists/*

# python deps
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY api /app

# 🔥 COPY FONT (INI BARU)
COPY fonts /app/fonts

ENV PYTHONPATH=/app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
